project: kornerstone
registry:
  registry_type: sql
  path: postgresql+psycopg://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/feast
offline_store:
  type: file
  format: parquet
  path: s3://mlflow/features
online_store:
  type: postgres
  host: postgres
  port: 5432
  database: feast
  db_schema: public
  user: ${POSTGRES_USER}
  password: ${POSTGRES_PASSWORD} 