apiVersion: v2
name: kornerstone
description: A Helm chart for Kornerstone ML Platform - A Get Up and Running ML Platform
type: application
version: 0.1.0
appVersion: "1.0.0"
dependencies:
  - name: postgresql
    version: "12.x.x"
    repository: "https://charts.bitnami.com/bitnami"
    condition: postgresql.enabled
  - name: minio
    version: "12.x.x"
    repository: "https://charts.bitnami.com/bitnami"
    condition: minio.enabled
  - name: mlflow
    version: "1.x.x"
    repository: "https://charts.bitnami.com/bitnami"
    condition: mlflow.enabled
  - name: argo-workflows
    version: "0.22.x"
    repository: "https://argoproj.github.io/argo-helm"
    condition: argo.enabled
  - name: kube-prometheus-stack
    version: "45.x.x"
    repository: "https://prometheus-community.github.io/helm-charts"
    condition: monitoring.enabled