apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: iris-rf
  annotations:
    serving.kserve.io/deploymentMode: Serverless
    serving.kserve.io/skip-webhook-validation: "true"
spec:
  predictor:
    serviceAccountName: kserve-sa
    model:
      modelFormat:
        name: sklearn
      runtime: kserve-mlserver
      storageUri: s3://mlflow/models/iris-rf
      resources:
        requests:
          cpu: 100m
          memory: 512Mi
        limits:
          cpu: 1
          memory: 1Gi

