apiVersion: v1
kind: ConfigMap
metadata:
  name: workflow-controller-configmap
data:
  config: |
    workflowDefaults:
      spec:
        serviceAccountName: argo-workflow-controller
    artifactRepository:
      archiveLogs: true
      s3:
        bucket: mlflow
        endpoint: minio:9000
        insecure: true
        accessKeySecret:
          name: minio-secret
          key: access-key
        secretKeySecret:
          name: minio-secret
          key: secret-key
    namespaceParallelism: 10