apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base/storage
- ../../base/argo
- ../../base/minio
- ../../base/postgres
- ../../base/mlflow
- ../../base/feast
- ../../base/kserve
- ../../base/tests
- secrets/minio-secret.yaml
- secrets/postgres-secret.yaml

namespace: kornerstone-ml 