apiVersion: "serving.kserve.io/v1beta1"
kind: InferenceService
metadata:
  name: diabetes-predictor
spec:
  predictor:
    serviceAccountName: kserve-sa
    model:
      modelFormat:
        name: sklearn
      storageUri: s3://mlflow/models/diabetes-model/
      storage:
        s3:
          endpoint: http://minio:9000
          bucket: mlflow
          secretAccessKey:
            name: minio-secret
            key: secret-key
          accessKeyID:
            name: minio-secret
            key: access-key 