apiVersion: v1
kind: ServiceAccount
metadata:
  name: kserve-sa
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: kserve-role
rules:
- apiGroups: ["serving.kserve.io"]
  resources: ["inferenceservices"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: kserve-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: kserve-role
subjects:
- kind: ServiceAccount
  name: kserve-sa 