apiVersion: v1
kind: ConfigMap
metadata:
  name: feast-config
data:
  feature_store.yaml: |
    project: kornerstone
    registry:
      path: postgresql+psycopg://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/feast
      registry_type: sql
    offline_store:
      type: remote
      host: minio
      port: 9000
    online_store:
      type: postgres
      host: postgres
      port: 5432
      database: feast
      db_schema: public
      user: ${POSTGRES_USER}
      password: ${POSTGRES_PASSWORD}
    entity_key_serialization_version: 2
    auth:
      type: no_auth