apiVersion: v1
kind: ConfigMap
metadata:
  name: feast-config
data:
  feature_store.yaml: |
    project: kornerstone
    registry: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/feast
    provider: local
    online_store:
      type: postgres
      connection_string: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/feast
    offline_store:
      type: file
      file_options:
        s3_endpoint_url: http://minio:9000
        s3_access_key_id: ${AWS_ACCESS_KEY_ID}
        s3_secret_access_key: ${AWS_SECRET_ACCESS_KEY} 