apiVersion: apps/v1
kind: Deployment
metadata:
  name: feast-feature-server
spec:
  selector:
    matchLabels:
      app: feast-feature-server
  template:
    metadata:
      labels:
        app: feast-feature-server
    spec:
      containers:
      - name: feast-feature-server
        image: feastdev/feature-server:latest
        ports:
        - containerPort: 6566
        volumeMounts:
        - name: feast-config
          mountPath: /etc/feast
        env:
        - name: FEAST_REGISTRY_PATH
          value: "postgresql://$(POSTGRES_USER):$(POSTGRES_PASSWORD)@postgres:5432/feast"
        - name: FEAST_S3_ENDPOINT_URL
          value: "http://minio:9000"
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: minio-secret
              key: access-key
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: minio-secret
              key: secret-key
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: username
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: password
      volumes:
      - name: feast-config
        configMap:
          name: feast-config 