{{- if .Values.feast.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-feast
  labels:
    {{- include "kornerstone.labels" . | nindent 4 }}
    app: feast
spec:
  type: {{ .Values.feast.service.type }}
  ports:
    - port: {{ .Values.feast.service.port }}
      targetPort: {{ .Values.feast.service.port }}
      protocol: TCP
      name: http
  selector:
    {{- include "kornerstone.selectorLabels" . | nindent 4 }}
    app: feast
{{- end }} 