{{- if .Values.kserve.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.kserve.serviceAccount.name }}
  labels:
    {{- include "kornerstone.labels" . | nindent 4 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ .Values.kserve.serviceAccount.name }}-role
  labels:
    {{- include "kornerstone.labels" . | nindent 4 }}
rules:
- apiGroups: [""]
  resources: ["pods", "services", "configmaps", "secrets"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["serving.kserve.io"]
  resources: ["inferenceservices", "predictors"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Values.kserve.serviceAccount.name }}-binding
  labels:
    {{- include "kornerstone.labels" . | nindent 4 }}
subjects:
- kind: ServiceAccount
  name: {{ .Values.kserve.serviceAccount.name }}
roleRef:
  kind: Role
  name: {{ .Values.kserve.serviceAccount.name }}-role
  apiGroup: rbac.authorization.k8s.io
{{- end }} 