{{- if .Values.kserve.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.kserve.serviceAccount.name }}
  labels:
    {{- include "kornerstone.labels" . | nindent 4 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ .Release.Name }}-kserve-role
  labels:
    {{- include "kornerstone.labels" . | nindent 4 }}
rules:
- apiGroups: ["serving.kserve.io"]
  resources: ["inferenceservices"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Release.Name }}-kserve-role-binding
  labels:
    {{- include "kornerstone.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ .Release.Name }}-kserve-role
subjects:
- kind: ServiceAccount
  name: {{ .Values.kserve.serviceAccount.name }}
{{- end }} 