{{- if .Values.minio.enabled -}}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Release.Name }}-minio-initializer
  labels:
    {{- include "kornerstone.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-5"  # Run early but after service account creation
    "helm.sh/hook-delete-policy": hook-succeeded,before-hook-creation
spec:
  ttlSecondsAfterFinished: 300  # Clean up after 5 minutes
  backoffLimit: 6
  template:
    metadata:
      labels:
        {{- include "kornerstone.labels" . | nindent 8 }}
        app: minio-init
    spec:
      restartPolicy: OnFailure
      containers:
      - name: noop
        image: alpine:3.20
        command: ["/bin/sh","-c"]
        args:
        - |
          echo "MinIO init hook is now a no-op because Bitnami MinIO subchart manages SA/Secret."
      serviceAccountName: {{ .Release.Name }}-minio-init-sa
---
# Service account for the initialization job
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}-minio-init-sa
  labels:
    {{- include "kornerstone.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "-10"
---
# RBAC for the initialization job
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ .Release.Name }}-minio-init-role
  labels:
    {{- include "kornerstone.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "-10"
rules:
- apiGroups: [""]
  resources: ["pods", "pods/log", "serviceaccounts", "secrets", "services"]
  verbs: ["get", "list", "watch", "create", "delete"]
- apiGroups: ["apps"]
  resources: ["deployments", "statefulsets"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Release.Name }}-minio-init-rolebinding
  labels:
    {{- include "kornerstone.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "-10"
subjects:
- kind: ServiceAccount
  name: {{ .Release.Name }}-minio-init-sa
roleRef:
  kind: Role
  name: {{ .Release.Name }}-minio-init-role
  apiGroup: rbac.authorization.k8s.io
{{- end -}} 