{{- if .Values.minio.enabled }}
# Create the MinIO service account explicitly before any other resources
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}-minio
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kornerstone.labels" . | nindent 4 }}
    app.kubernetes.io/name: minio
    app.kubernetes.io/instance: {{ .Release.Name }}
  annotations:
    # Use a priority annotation to ensure this is created very early
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "-20"
    "helm.sh/resource-policy": "keep"
{{- end }} 