{{- if .Values.mlflow.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-mlflow
  labels:
    {{- include "kornerstone.labels" . | nindent 4 }}
    app: mlflow
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "kornerstone.selectorLabels" . | nindent 6 }}
      app: mlflow
  template:
    metadata:
      labels:
        {{- include "kornerstone.selectorLabels" . | nindent 8 }}
        app: mlflow
    spec:
      initContainers:
      {{- include "kornerstone.postgresql.initContainer" . | nindent 6 }}
      {{- include "kornerstone.minio.initContainer" . | nindent 6 }}
      {{- include "kornerstone.mlflow.dbInit" . | nindent 6 }}
      {{- include "kornerstone.minio.bucketInit" . | nindent 6 }}
      containers:
      - name: mlflow
        image: "ghcr.io/mlflow/mlflow:v2.10.0"
        imagePullPolicy: IfNotPresent
        command: ["/bin/sh","-c"]
        args:
          - |
            pip install --no-cache-dir psycopg2-binary==2.9.9 && \
            mlflow server \
              --host=0.0.0.0 \
              --port={{ .Values.mlflow.service.port }} \
              --backend-store-uri=postgresql://{{ .Values.postgresql.auth.username }}:${POSTGRES_PASSWORD}@{{ .Release.Name }}-postgresql:5432/mlflow \
              --default-artifact-root=s3://mlflow/artifacts \
              --workers=4 \
              --serve-artifacts
        ports:
        - name: http
          containerPort: {{ .Values.mlflow.service.port }}
        env:
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-postgresql
              key: password
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-minio
              key: root-user
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-minio
              key: root-password
        - name: MLFLOW_S3_ENDPOINT_URL
          value: "http://{{ .Release.Name }}-minio:{{ .Values.minio.service.ports.api }}"
        - name: MLFLOW_S3_IGNORE_TLS
          value: "true"
        - name: MLFLOW_TRACKING_URI
          value: "http://{{ .Release.Name }}-mlflow:{{ .Values.mlflow.service.port }}"
        - name: MLFLOW_ARTIFACTS_DESTINATION
          value: "s3://mlflow/artifacts"
        livenessProbe:
          httpGet:
            path: /health
            port: {{ .Values.mlflow.service.port }}
          initialDelaySeconds: 120
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
            port: {{ .Values.mlflow.service.port }}
          initialDelaySeconds: 60
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        resources:
          limits:
            cpu: 1000m
            memory: 1Gi
          requests:
            cpu: 200m
            memory: 512Mi
        volumeMounts:
        - name: tmp-volume
          mountPath: /tmp
      volumes:
      - name: tmp-volume
        emptyDir: {}
{{- end }} 