{{- if .Values.mlflow.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-mlflow
  labels:
    {{- include "kornerstone.labels" . | nindent 4 }}
    app: mlflow
spec:
  type: {{ .Values.mlflow.service.type }}
  ports:
  - port: {{ .Values.mlflow.service.port }}
    targetPort: http
    protocol: TCP
    name: http
  selector:
    {{- include "kornerstone.selectorLabels" . | nindent 4 }}
    app: mlflow
{{- end }} 